"""empty message

Revision ID: 888fb6712246
Revises: e8d6dde32d0d
Create Date: 2020-04-28 17:39:33.652264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '888fb6712246'
down_revision = 'e8d6dde32d0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('homepage_link', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('homepage_link', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'homepage_link')
    op.drop_column('artist', 'homepage_link')
    # ### end Alembic commands ###
